services:
  - type: web
    name: encontro-veras-saldanha-backend
    region: oregon
    env: python
    pythonVersion: "3.12.3"
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python src/manage.py create_tables
    startCommand: gunicorn --workers 1 src.main:app  
    staticFiles:
      - path: /static
        destination: src/static
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: veras-saldanha-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /api/health
    plan: free
