services:
  - type: web
    name: encontro-veras-saldanha-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.main:app
    staticFiles:
      - path: /static
        destination: src/static
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true