services:
  - type: web
    name: encontro-veras-saldanha-backend
    region: oregon
    env: python
    pythonVersion: "3.12"
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      cd src && python manage.py create_tables
    startCommand: cd src && gunicorn --workers 1 --bind 0.0.0.0:$PORT main:app
    staticFiles:
      - path: /static
        destination: src/static
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: veras-saldanha-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /api/health
    plan: free

databases:
  - name: veras-saldanha-db
    databaseName: veras_saldanha
    user: veras_user
    plan: free

